### ISSUE TITLE
Ignore \n

### ISSUE THREAD

**Issue by caspahouzer** [FokkeZB/ti-i18n#14]
Please set "\n" as ignored. Otherwise the xml breaks

**Comment by FokkeZB** [comment]
How do you mean exactly? Ignore when doing what?

**Comment by caspahouzer** [comment]
Oh sorry :neutral_face: 

I mean on adding the strings to the strings.xml.

Example: L('Hello\nWorld') becomes:

<string name="Hello\nWorld">Hello
World</string>

**Comment by caspahouzer** [comment]
Works!
