### ISSUE TITLE
[enhancement] order strings

### ISSUE THREAD

**Issue by caspahouzer** [FokkeZB/ti-i18n#15]
It would be nice to have an option -o [asc,desc] to order the strings alphabetically on adding.

Then it's easier to find strings in the xml

**Comment by FokkeZB** [comment]
Maybe it would better be a dedicated command?

**Comment by caspahouzer** [comment]
However :-)

**Comment by FokkeZB** [comment]
I have no time to look at both of the issues atm, but feel free to do PR. I'd prefer a separate command.

**Comment by caspahouzer** [comment]
If I would be able to code, I would do it. But unfortunately I don't. But I can wait ;)

**Comment by FokkeZB** [comment]
Added the command `sort`.

**Comment by caspahouzer** [comment]
Thank you very much! :+1:

**Comment by caspahouzer** [comment]
I'm not really sure how to use it.

In project path with plugged ti-i18n
ti i18n sort 
does nothing with my files

**Comment by FokkeZB** [comment]
Try `ti-i18n sort`

**Comment by caspahouzer** [comment]
Sorry, but adding strings failed with new version 0.5.1

**Comment by caspahouzer** [comment]
opened https://github.com/FokkeZB/ti-i18n/issues/16

**Comment by caspahouzer** [comment]
ti-18n sort does nothing too. except for you sort the strings randomly ;)

**Comment by caspahouzer** [comment]
My console output:

~~~
sebastian-MacBook-Pro:Fantastic Library 4 sebastian$ ti-i18n sort
[INFO] Found 1 languages in: /Volumes/Data/Users/sebastian/Develop/AppName/i18n
~~~

**Comment by caspahouzer** [comment]
Works 99%

Maybe I'm a little bit picky, but the lowercase strings are sorted at the end. The rest is sorted right.

**Comment by FokkeZB** [comment]
Could you try master?

```
sudo npm install -g fokkezb/ti-i18n
```

**Comment by caspahouzer** [comment]
Perfect! Thanks a lot for this quick response!!
