### ISSUE TITLE
sort deletes double quotes

### ISSUE THREAD

**Issue by caspahouzer** [FokkeZB/ti-i18n#18]
I have some strings which are like this

~~~
<string name="Episode {partNumber} added">Episode "{partNumber}" added</string>
~~~

ti i18n sort turns the line into

~~~
<string name="Episode {partNumber} added">Episode {partNumber}" added</string>
~~~

**Comment by FokkeZB** [comment]
I have no idea why [this](https://github.com/FokkeZB/ti-i18n/commit/028e0c9e3ce4045d288ce99512d2509af3cb0884#diff-2c7794dc207c10d87aa4dcb6e4ff1b0bR19) filter was here, but I removed it. Let's see what problems we run into now ;)

**Comment by FokkeZB** [comment]
Thx ;)

**Comment by caspahouzer** [comment]
Confirmed as fixed. Thank you!
